/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Charity {
  'id' : bigint,
  'featured' : boolean,
  'name' : string,
  'eventsList' : Array<string>,
  'description' : string,
}
export interface Draw {
  'id' : bigint,
  'status' : DrawStatus,
  'drawLogic' : DrawLogic,
  'jackpot' : bigint,
  'drawDate' : bigint,
  'winningNumbers' : Array<bigint>,
  'prizePool' : bigint,
}
export type DrawLogic = { 'algorithmic' : null } |
  { 'random' : null };
export type DrawStatus = { 'simulated' : null } |
  { 'pending' : null } |
  { 'published' : null };
export interface GolfScore { 'score' : bigint, 'dateText' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface User {
  'golfScores' : Array<GolfScore>,
  'name' : string,
  'role' : { 'admin' : null } |
    { 'subscriber' : null },
  'selectedCharityId' : [] | [bigint],
  'email' : string,
  'subscriptionActive' : boolean,
  'charityContributionPercent' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Winner {
  'paymentStatus' : { 'pending' : null } |
    { 'paid' : null },
  'prizeAmount' : bigint,
  'matchCount' : bigint,
  'userId' : Principal,
  'proofBlobId' : [] | [string],
  'drawId' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCharity' : ActorMethod<[Charity], undefined>,
  'addGolfScore' : ActorMethod<[bigint, string], undefined>,
  'addWinner' : ActorMethod<[Winner], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDraw' : ActorMethod<[Draw], undefined>,
  'deleteCharity' : ActorMethod<[bigint], undefined>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], User>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharities' : ActorMethod<[], Array<Charity>>,
  'getFeaturedCharities' : ActorMethod<[], Array<Charity>>,
  'getGolfScores' : ActorMethod<[Principal], Array<GolfScore>>,
  'getPublishedDraws' : ActorMethod<[], Array<Draw>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalCharityContributions' : ActorMethod<[], bigint>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], User>,
  'getWinnersByDraw' : ActorMethod<[bigint], Array<Winner>>,
  'getWinnersByUser' : ActorMethod<[Principal], Array<Winner>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserRegistered' : ActorMethod<[], boolean>,
  'markWinnerAsPaid' : ActorMethod<[bigint], undefined>,
  'publishDraw' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCallerProfile' : ActorMethod<
    [string, string, [] | [bigint], bigint],
    undefined
  >,
  'updateCharity' : ActorMethod<[Charity], undefined>,
  'updateDraw' : ActorMethod<[Draw], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];