/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Charity = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'eventsList' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const Winner = IDL.Record({
  'paymentStatus' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
  'prizeAmount' : IDL.Nat,
  'matchCount' : IDL.Nat,
  'userId' : IDL.Principal,
  'proofBlobId' : IDL.Opt(IDL.Text),
  'drawId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const DrawStatus = IDL.Variant({
  'simulated' : IDL.Null,
  'pending' : IDL.Null,
  'published' : IDL.Null,
});
export const DrawLogic = IDL.Variant({
  'algorithmic' : IDL.Null,
  'random' : IDL.Null,
});
export const Draw = IDL.Record({
  'id' : IDL.Nat,
  'status' : DrawStatus,
  'drawLogic' : DrawLogic,
  'jackpot' : IDL.Nat,
  'drawDate' : IDL.Int,
  'winningNumbers' : IDL.Vec(IDL.Nat),
  'prizePool' : IDL.Nat,
});
export const GolfScore = IDL.Record({
  'score' : IDL.Nat,
  'dateText' : IDL.Text,
});
export const User = IDL.Record({
  'golfScores' : IDL.Vec(GolfScore),
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'admin' : IDL.Null, 'subscriber' : IDL.Null }),
  'selectedCharityId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'subscriptionActive' : IDL.Bool,
  'charityContributionPercent' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCharity' : IDL.Func([Charity], [], []),
  'addGolfScore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addWinner' : IDL.Func([Winner], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDraw' : IDL.Func([Draw], [], []),
  'deleteCharity' : IDL.Func([IDL.Nat], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [User], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharities' : IDL.Func([], [IDL.Vec(Charity)], ['query']),
  'getFeaturedCharities' : IDL.Func([], [IDL.Vec(Charity)], ['query']),
  'getGolfScores' : IDL.Func([IDL.Principal], [IDL.Vec(GolfScore)], ['query']),
  'getPublishedDraws' : IDL.Func([], [IDL.Vec(Draw)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalCharityContributions' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [User], ['query']),
  'getWinnersByDraw' : IDL.Func([IDL.Nat], [IDL.Vec(Winner)], ['query']),
  'getWinnersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Winner)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'markWinnerAsPaid' : IDL.Func([IDL.Nat], [], []),
  'publishDraw' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCallerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
      [],
      [],
    ),
  'updateCharity' : IDL.Func([Charity], [], []),
  'updateDraw' : IDL.Func([Draw], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Charity = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'eventsList' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const Winner = IDL.Record({
    'paymentStatus' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
    'prizeAmount' : IDL.Nat,
    'matchCount' : IDL.Nat,
    'userId' : IDL.Principal,
    'proofBlobId' : IDL.Opt(IDL.Text),
    'drawId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const DrawStatus = IDL.Variant({
    'simulated' : IDL.Null,
    'pending' : IDL.Null,
    'published' : IDL.Null,
  });
  const DrawLogic = IDL.Variant({
    'algorithmic' : IDL.Null,
    'random' : IDL.Null,
  });
  const Draw = IDL.Record({
    'id' : IDL.Nat,
    'status' : DrawStatus,
    'drawLogic' : DrawLogic,
    'jackpot' : IDL.Nat,
    'drawDate' : IDL.Int,
    'winningNumbers' : IDL.Vec(IDL.Nat),
    'prizePool' : IDL.Nat,
  });
  const GolfScore = IDL.Record({ 'score' : IDL.Nat, 'dateText' : IDL.Text });
  const User = IDL.Record({
    'golfScores' : IDL.Vec(GolfScore),
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'admin' : IDL.Null, 'subscriber' : IDL.Null }),
    'selectedCharityId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'subscriptionActive' : IDL.Bool,
    'charityContributionPercent' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCharity' : IDL.Func([Charity], [], []),
    'addGolfScore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addWinner' : IDL.Func([Winner], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDraw' : IDL.Func([Draw], [], []),
    'deleteCharity' : IDL.Func([IDL.Nat], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [User], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharities' : IDL.Func([], [IDL.Vec(Charity)], ['query']),
    'getFeaturedCharities' : IDL.Func([], [IDL.Vec(Charity)], ['query']),
    'getGolfScores' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GolfScore)],
        ['query'],
      ),
    'getPublishedDraws' : IDL.Func([], [IDL.Vec(Draw)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalCharityContributions' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [User], ['query']),
    'getWinnersByDraw' : IDL.Func([IDL.Nat], [IDL.Vec(Winner)], ['query']),
    'getWinnersByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Winner)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'markWinnerAsPaid' : IDL.Func([IDL.Nat], [], []),
    'publishDraw' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCallerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
        [],
        [],
      ),
    'updateCharity' : IDL.Func([Charity], [], []),
    'updateDraw' : IDL.Func([Draw], [], []),
  });
};

export const init = ({ IDL }) => { return []; };