/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Draw {
    id: bigint;
    status: DrawStatus;
    drawLogic: DrawLogic;
    jackpot: bigint;
    drawDate: bigint;
    winningNumbers: Array<bigint>;
    prizePool: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface User {
    golfScores: Array<GolfScore>;
    name: string;
    role: Variant_admin_subscriber;
    selectedCharityId?: bigint;
    email: string;
    subscriptionActive: boolean;
    charityContributionPercent: bigint;
}
export interface Charity {
    id: bigint;
    featured: boolean;
    name: string;
    eventsList: Array<string>;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface GolfScore {
    score: bigint;
    dateText: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Winner {
    paymentStatus: Variant_pending_paid;
    prizeAmount: bigint;
    matchCount: bigint;
    userId: Principal;
    proofBlobId?: string;
    drawId: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DrawLogic {
    algorithmic = "algorithmic",
    random = "random"
}
export enum DrawStatus {
    simulated = "simulated",
    pending = "pending",
    published = "published"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_admin_subscriber {
    admin = "admin",
    subscriber = "subscriber"
}
export enum Variant_pending_paid {
    pending = "pending",
    paid = "paid"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCharity(charity: Charity): Promise<void>;
    addGolfScore(score: bigint, dateText: string): Promise<void>;
    addWinner(winner: Winner): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createDraw(draw: Draw): Promise<void>;
    deleteCharity(charityId: bigint): Promise<void>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<User>;
    getCallerUserRole(): Promise<UserRole>;
    getCharities(): Promise<Array<Charity>>;
    getFeaturedCharities(): Promise<Array<Charity>>;
    getGolfScores(user: Principal): Promise<Array<GolfScore>>;
    getPublishedDraws(): Promise<Array<Draw>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTotalCharityContributions(): Promise<bigint>;
    getTotalUsers(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<User>;
    getWinnersByDraw(drawId: bigint): Promise<Array<Winner>>;
    getWinnersByUser(user: Principal): Promise<Array<Winner>>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isUserRegistered(): Promise<boolean>;
    markWinnerAsPaid(winnerId: bigint): Promise<void>;
    publishDraw(drawId: bigint): Promise<void>;
    registerUser(name: string, email: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCallerProfile(name: string, email: string, selectedCharityId: bigint | null, charityContributionPercent: bigint): Promise<void>;
    updateCharity(charity: Charity): Promise<void>;
    updateDraw(draw: Draw): Promise<void>;
}
import type { Draw as _Draw, DrawLogic as _DrawLogic, DrawStatus as _DrawStatus, GolfScore as _GolfScore, StripeSessionStatus as _StripeSessionStatus, User as _User, UserRole as _UserRole, Winner as _Winner, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCharity(arg0: Charity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCharity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCharity(arg0);
            return result;
        }
    }
    async addGolfScore(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGolfScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGolfScore(arg0, arg1);
            return result;
        }
    }
    async addWinner(arg0: Winner): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWinner(to_candid_Winner_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWinner(to_candid_Winner_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDraw(arg0: Draw): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDraw(to_candid_Draw_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDraw(to_candid_Draw_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCharity(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCharity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCharity(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_User_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_User_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharities(): Promise<Array<Charity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharities();
            return result;
        }
    }
    async getFeaturedCharities(): Promise<Array<Charity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedCharities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedCharities();
            return result;
        }
    }
    async getGolfScores(arg0: Principal): Promise<Array<GolfScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGolfScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGolfScores(arg0);
            return result;
        }
    }
    async getPublishedDraws(): Promise<Array<Draw>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedDraws();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedDraws();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalCharityContributions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCharityContributions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCharityContributions();
            return result;
        }
    }
    async getTotalUsers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUsers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_User_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_User_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWinnersByDraw(arg0: bigint): Promise<Array<Winner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinnersByDraw(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinnersByDraw(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWinnersByUser(arg0: Principal): Promise<Array<Winner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinnersByUser(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinnersByUser(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isUserRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserRegistered();
            return result;
        }
    }
    async markWinnerAsPaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWinnerAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWinnerAsPaid(arg0);
            return result;
        }
    }
    async publishDraw(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishDraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishDraw(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCallerProfile(arg0: string, arg1: string, arg2: bigint | null, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerProfile(arg0, arg1, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerProfile(arg0, arg1, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateCharity(arg0: Charity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCharity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCharity(arg0);
            return result;
        }
    }
    async updateDraw(arg0: Draw): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDraw(to_candid_Draw_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDraw(to_candid_Draw_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DrawLogic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrawLogic): DrawLogic {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_DrawStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrawStatus): DrawStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Draw_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Draw): Draw {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_User_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Winner_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Winner): Winner {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    golfScores: Array<_GolfScore>;
    name: string;
    role: {
        admin: null;
    } | {
        subscriber: null;
    };
    selectedCharityId: [] | [bigint];
    email: string;
    subscriptionActive: boolean;
    charityContributionPercent: bigint;
}): {
    golfScores: Array<GolfScore>;
    name: string;
    role: Variant_admin_subscriber;
    selectedCharityId?: bigint;
    email: string;
    subscriptionActive: boolean;
    charityContributionPercent: bigint;
} {
    return {
        golfScores: value.golfScores,
        name: value.name,
        role: from_candid_variant_n22(_uploadFile, _downloadFile, value.role),
        selectedCharityId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.selectedCharityId)),
        email: value.email,
        subscriptionActive: value.subscriptionActive,
        charityContributionPercent: value.charityContributionPercent
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DrawStatus;
    drawLogic: _DrawLogic;
    jackpot: bigint;
    drawDate: bigint;
    winningNumbers: Array<bigint>;
    prizePool: bigint;
}): {
    id: bigint;
    status: DrawStatus;
    drawLogic: DrawLogic;
    jackpot: bigint;
    drawDate: bigint;
    winningNumbers: Array<bigint>;
    prizePool: bigint;
} {
    return {
        id: value.id,
        status: from_candid_DrawStatus_n28(_uploadFile, _downloadFile, value.status),
        drawLogic: from_candid_DrawLogic_n30(_uploadFile, _downloadFile, value.drawLogic),
        jackpot: value.jackpot,
        drawDate: value.drawDate,
        winningNumbers: value.winningNumbers,
        prizePool: value.prizePool
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: {
        pending: null;
    } | {
        paid: null;
    };
    prizeAmount: bigint;
    matchCount: bigint;
    userId: Principal;
    proofBlobId: [] | [string];
    drawId: bigint;
}): {
    paymentStatus: Variant_pending_paid;
    prizeAmount: bigint;
    matchCount: bigint;
    userId: Principal;
    proofBlobId?: string;
    drawId: bigint;
} {
    return {
        paymentStatus: from_candid_variant_n39(_uploadFile, _downloadFile, value.paymentStatus),
        prizeAmount: value.prizeAmount,
        matchCount: value.matchCount,
        userId: value.userId,
        proofBlobId: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.proofBlobId)),
        drawId: value.drawId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    subscriber: null;
}): Variant_admin_subscriber {
    return "admin" in value ? Variant_admin_subscriber.admin : "subscriber" in value ? Variant_admin_subscriber.subscriber : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    simulated: null;
} | {
    pending: null;
} | {
    published: null;
}): DrawStatus {
    return "simulated" in value ? DrawStatus.simulated : "pending" in value ? DrawStatus.pending : "published" in value ? DrawStatus.published : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    algorithmic: null;
} | {
    random: null;
}): DrawLogic {
    return "algorithmic" in value ? DrawLogic.algorithmic : "random" in value ? DrawLogic.random : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n34(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): Variant_pending_paid {
    return "pending" in value ? Variant_pending_paid.pending : "paid" in value ? Variant_pending_paid.paid : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Draw>): Array<Draw> {
    return value.map((x)=>from_candid_Draw_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Winner>): Array<Winner> {
    return value.map((x)=>from_candid_Winner_n37(_uploadFile, _downloadFile, x));
}
function to_candid_DrawLogic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrawLogic): _DrawLogic {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_DrawStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrawStatus): _DrawStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Draw_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Draw): _Draw {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Winner_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Winner): _Winner {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: DrawStatus;
    drawLogic: DrawLogic;
    jackpot: bigint;
    drawDate: bigint;
    winningNumbers: Array<bigint>;
    prizePool: bigint;
}): {
    id: bigint;
    status: _DrawStatus;
    drawLogic: _DrawLogic;
    jackpot: bigint;
    drawDate: bigint;
    winningNumbers: Array<bigint>;
    prizePool: bigint;
} {
    return {
        id: value.id,
        status: to_candid_DrawStatus_n15(_uploadFile, _downloadFile, value.status),
        drawLogic: to_candid_DrawLogic_n17(_uploadFile, _downloadFile, value.drawLogic),
        jackpot: value.jackpot,
        drawDate: value.drawDate,
        winningNumbers: value.winningNumbers,
        prizePool: value.prizePool
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: Variant_pending_paid;
    prizeAmount: bigint;
    matchCount: bigint;
    userId: Principal;
    proofBlobId?: string;
    drawId: bigint;
}): {
    paymentStatus: {
        pending: null;
    } | {
        paid: null;
    };
    prizeAmount: bigint;
    matchCount: bigint;
    userId: Principal;
    proofBlobId: [] | [string];
    drawId: bigint;
} {
    return {
        paymentStatus: to_candid_variant_n10(_uploadFile, _downloadFile, value.paymentStatus),
        prizeAmount: value.prizeAmount,
        matchCount: value.matchCount,
        userId: value.userId,
        proofBlobId: value.proofBlobId ? candid_some(value.proofBlobId) : candid_none(),
        drawId: value.drawId
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_paid): {
    pending: null;
} | {
    paid: null;
} {
    return value == Variant_pending_paid.pending ? {
        pending: null
    } : value == Variant_pending_paid.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrawStatus): {
    simulated: null;
} | {
    pending: null;
} | {
    published: null;
} {
    return value == DrawStatus.simulated ? {
        simulated: null
    } : value == DrawStatus.pending ? {
        pending: null
    } : value == DrawStatus.published ? {
        published: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrawLogic): {
    algorithmic: null;
} | {
    random: null;
} {
    return value == DrawLogic.algorithmic ? {
        algorithmic: null
    } : value == DrawLogic.random ? {
        random: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
